# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='员工姓名', max_length=50)),
                ('gender', models.CharField(choices=[('男', 'male'), ('女', 'female')], default='male', help_text='性别', max_length=11)),
                ('email', models.EmailField(default='', help_text='邮箱', max_length=254)),
                ('age', models.IntegerField(default='', help_text='年龄')),
                ('mobile', models.CharField(default='', help_text='手机号码', max_length=11)),
                ('user', models.OneToOneField(help_text='商家', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seiler',
                'verbose_name_plural': 'Seilers',
            },
        ),
    ]
