# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finish_time',
            field=models.DateTimeField(help_text='支付完成时间', null=True),
        ),
    ]
