# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20180525_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinghistory',
            name='state',
            field=models.IntegerField(default=0, help_text='0--->未评价，1--->已评价'),
        ),
    ]
